# Checks related only to PRs and not code
name: PR Deploy

# concurrency:
#   # TODO: make this stop if running miltiple for one pr
#   group: '${{ github.workflow }} - ${{ github.head_ref }}'
#   cancel-in-progress: true

env:
  NODE_VERSION: '16.13.2' # should match version in .nvmrc

on:
  deployment

jobs:
  testing:
    name: Testing deployment event
    runs-on: ubuntu-latest
    steps:
      - name: Print context - Testing 2
        shell: python
        run: |
          print("""${{ toJSON(github) }}""")
      - name: Print event
        shell: python
        run: |
          print("""${{ toJSON(github.event) }}""")
      - name: Print payload
        shell: python
        run: |
          print("""${{ toJSON(github.event) }}""")
      - name: Checkout repo
        uses: actions/checkout@v2
        with:
          repository: elastic/elastic-charts
          ssh-strict: true
          persist-credentials: false
          clean: true
          fetch-depth: 1
          lfs: false
          submodules: false
          ref: ${{ github.event.deployment.ref }}
      - run: ls

      - name: Deploy build to firebase
        id: deploy
        uses: FirebaseExtended/action-hosting-deploy@v0
        with:
          expires: 14d # this updates for every deploy
          entryPoint: 'e2e-server'
          repoToken: '${{ secrets.GITHUB_TOKEN }}'
          # See https://console.cloud.google.com/iam-admin/iam?project=ech-e2e-ci
          firebaseServiceAccount: '${{ secrets.FIREBASE_SERVICE_ACCOUNT_ECH_E2E_CI }}'
          projectId: ech-e2e-ci
          channelId: 'pr1568'
      - name: Outputs
        shell: python
        run: |
          print("""${{ toJSON(steps.deploy.outputs) }}""")
