# Checks related only to PRs and not code
name: PR Deploy

# concurrency:
#   # TODO: make this stop if running miltiple for one pr
#   group: '${{ github.workflow }} - ${{ github.head_ref }}'
#   cancel-in-progress: true

env:
  NODE_VERSION: '16.13.2' # should match version in .nvmrc

on:
  deployment

jobs:
  testing:
    name: Testing deployment event
    runs-on: ubuntu-latest
    steps:
      # - name: Checkout repo
      #   uses: actions/checkout@v2
      - name: Print context
        shell: python
        run: |
          print("""${{ toJSON(github) }}""")
      - name: Print event
        shell: python
        run: |
          print("""${{ toJSON(github.event) }}""")
      # - name: Deploy build to firebase
      #   id: deploy
      #   uses: FirebaseExtended/action-hosting-deploy@v0
      #   with:
      #     expires: 14d # this updates for every deploy
      #     entryPoint: 'e2e-server'
      #     repoToken: '${{ secrets.GITHUB_TOKEN }}'
      #     # See https://console.cloud.google.com/iam-admin/iam?project=ech-e2e-ci
      #     firebaseServiceAccount: '${{ secrets.FIREBASE_SERVICE_ACCOUNT_ECH_E2E_CI }}'
      #     projectId: ech-e2e-ci
      # - name: Outputs
      #   shell: python
      #   run: |
      #     print("""${{ toJSON(steps.deploy.outputs) }}""")
