# Triggers a deployment task for each new pr
name: PR Deploy Trigger

env:
  NODE_VERSION: '16.13.2' # should match version in .nvmrc

# Precautionary with using pull_request_target
permissions:
  statuses: none
  actions: none
  checks: none
  pull-requests: none
  contents: none
  deployments: write
  issues: none
  packages: none
  repository-projects: none
  security-events: none

on:
  # Needed to allow forks to access secrets in ci with limited scope
  # This is why we limit 3rd party contributors running actions
  # See https://docs.github.com/en/actions/reference/events-that-trigger-workflows#pull_request_target
  pull_request_target:
    branches:
      # - master
      # - alpha
      - next
      # - '[0-9]+.[0-9]+.[0-9]+'
      # - '[0-9]+.[0-9]+.x'
      # - '[0-9]+.x'

jobs:
  testing:
    name: Testing deployment event
    runs-on: ubuntu-latest
    environment: dev
    steps:
      - name: Checkout repo
        uses: actions/checkout@v2
      - name: Print context
        shell: python
        run: |
          print("""${{ toJSON(github) }}""")
      - name: Print event
        shell: python
        run: |
          print("""${{ toJSON(github.event) }}""")
      - name: Print event
        shell: python
        run: |
          print("""${{ toJSON(github.event) }}""")
      - uses: octokit/request-action@v2.x
        id: deployment
        with:
          # https://docs.github.com/en/rest/reference/deployments#create-a-deployment
          route: POST /repos/{repo}/deployments
          repo: ${{ github.repository }}
          ref: ${{ github.sha }}
          auto_merge: false # use branch as is without merging with base
          required_contexts: '[]'
          environment: dev
          description: "Deployment for PR #${{ github.event.pull_request.number }}"
          payload: ${{ toJSON(github) }}
          # payload: |
          #   {
          #     "key": "value",
          #   }
        env:
          GITHUB_TOKEN: ${{ secrets.GH_DEPLOYMENT_TOKEN }}
      - name: Print outputs
        if: ${{ always() }}
        shell: python
        run: |
          print("""${{ toJSON(steps.deployment.outputs) }}""")
