name: 'PR Sync Check'

concurrency:
  group: pr_sync_checker
  cancel-in-progress: true

on:
  push:
    branches:
      - master
      - alpha
      - next
      - '[0-9]+.[0-9]+.[0-9]+'
      - '[0-9]+.[0-9]+.x'
      - '[0-9]+.x'

jobs:
  fetch:
    runs-on: ubuntu-latest
    outputs:
      matrix: ${{ steps.matrix.outputs.json }}
    steps:
      - name: Fetch open pull requests
        id: fetch
        uses: octokit/request-action@v2.x
        with:
          route: GET /repos/{repo}/pulls?state=open
          repo: ${{ github.repository }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - name: Store matrix
        id: matrix
        uses: nickofthyme/object-remap@v1
        with:
          include.*.number: ${{ toJSON(fromJSON(steps.fetch.outputs.data).*.number) }}
          include.*.title: ${{ toJSON(fromJSON(steps.fetch.outputs.data).*.title) }}
          include.*.head_sha: ${{ toJSON(fromJSON(steps.fetch.outputs.data).*.head.sha) }}
          include.*.base_ref: ${{ toJSON(fromJSON(steps.fetch.outputs.data).*.base.ref) }}
          include.*.base_sha: ${{ toJSON(fromJSON(steps.fetch.outputs.data).*.base.sha) }}

  base-status-check:
    name: 'PR #${{ matrix.number }} - ${{ matrix.title }}'
    runs-on: ubuntu-latest
    needs: fetch
    strategy:
      matrix: ${{ fromJSON(needs.fetch.outputs.matrix) }}
      fail-fast: false
    steps:
      - name: Check out branch # needed to use local action
        uses: actions/checkout@v2
        with:
          persist-credentials: false
      - name: Install local action packages
        run: npm --prefix ./.github/actions/base_diff_check ci
      - name: Check PR sync status
        uses: ./.github/actions/base_diff_check
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          base-ref: ${{ matrix.baseRef }}
          base-sha: ${{ matrix.baseSha }}
          head-sha: ${{ matrix.headSha }}
          pr-number: ${{ matrix.number }}
          silent: true # prevent failed check on base branch
